### PR TITLE
Update D0 prefilter cuts

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by lvermunt** [comment]
Hi @benedikt-voelkel. Do you really want to tighten the single track pT for the prongs from 0.3 (set in the AliESDTrackCut object) to 0.5 using the topological cuts? Isn't this too tight for D0 at low pT?

Other changes are fine for me.

**Comment by benedikt-voelkel** [comment]
@ginnocen I think we agreed on 0.5, right? From what we saw in the plots we had a look at?

**Comment by ginnocen** [comment]
Hi Benedikt, 
I would probably keep it to 0.3 in the creation of the trees so that we have a bit more of phase space for the D0 1-2 GeV pt bin. And we apply 0.5 when we convert the trees to pkl. What you think?
Cheers GM

**Comment by benedikt-voelkel** [comment]
@ginnocen @lvermunt you might want to have a look

**Comment by lvermunt** [comment]
Hi @benedikt-voelkel. Could you keep the whichCuts=1 option for Dstar as it was? These are from the recently published pp@5TeV analysis, directly taken from the macros I used to generate the cutobjects for this analysis. I'm asking because some of the changes of Marco look a bit weird to me.

Another thing. Because of the soft-pion in the Dstar decay that is basically primary, we generally don't remove the daughters from the primary vertex for Dstar.

Then I have a doubt about your change of 0.25 -> 0.1 for the D0 invariant mass cut. We cut away the whole sideband regions with this (see https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/database_ml_parameters_D0pp.yml#L180). For Dstar this change is fine btw

**Comment by lvermunt** [comment]
To be complete also here, for the Dstar we are storing a way too large sideband for the background candidates. We can reduce the output size of the Dstar TTree by a factor ~4.5 by changing 0.1 -> 0.025 (element 11 of the array (so cutsArrayDstartoKpipi[10]))

**Pull request closed without merging**
